### PR TITLE
Implement automatic es-react build using Rollup

### LINKED ISSUE #4: Export named `React` members
A lot of libraries use named exports from React. And IIRC we have to manually enumerate those. I've got a temp shim looking like this that might be a useful starting point (would be nice to automate this maybe like `react-ecmascript` project does...)

```js
/**
 * es-react needs exports for the individual methods.
 *
 * This is a shim until things are fixed from:
 * https://unpkg.com/browse/react-ecmascript@1.4.4/react.development.mjs
 */
import React from 'https://unpkg.com/es-react@16.8.60/src/react.js';

export default React;

const {
  Children,

  createRef,
  Component,
  PureComponent,

  createContext,
  forwardRef,
  lazy,
  memo,

  useCallback,
  useContext,
  useEffect,
  useImperativeHandle,
  useDebugValue,
  useLayoutEffect,
  useMemo,
  useReducer,
  useRef,
  useState,

  Fragment,
  StrictMode,
  Suspense,

  createElement,
  cloneElement,
  createFactory,
  isValidElement,

  version,

  unstable_ConcurrentMode,
  unstable_Profiler,

  __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED
} = React;
export {
  Children,

  createRef,
  Component,
  PureComponent,

  createContext,
  forwardRef,
  lazy,
  memo,

  useCallback,
  useContext,
  useEffect,
  useImperativeHandle,
  useDebugValue,
  useLayoutEffect,
  useMemo,
  useReducer,
  useRef,
  useState,

  Fragment,
  StrictMode,
  Suspense,

  createElement,
  cloneElement,
  createFactory,
  isValidElement,

  version,

  unstable_ConcurrentMode,
  unstable_Profiler,

  __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED
};
```

### PR DESCRIPTION
**Pull request by kitten**
Fix #4

### CODE REVIEW

**Comment by ryan-roemer** [comment]
I think you need to manually `git rm index.js` as it's in the diff (?)

**Comment by kitten** [comment]
This now creates a code-split Rollup build with separate bundles: `react.js`, `react-dom.js` and `prop-types.js`. The `index.js` file points to these generated bundles and also exports `React`, `ReactDOM` and `PropTypes`, apart from exporting all of `react.js`. This means that these bundles can also be accessed separately.

The generated `dev/` output is identical with the other output in the root folder, but is just the `development` build (nothing surprising then). This also adds a `dev/package.json` file, since that's now a separate subfolder with files, but `unpkg.com` will resolve `/dev/index.js` automatically for `es-react/dev` anyway.

**Comment by znk** [comment]
Wow @kitten, impressive work! I came across that PR after looking at `@pika/web`, and also thanks for publishing to last version. How do you think handling the new `next` and `experimental` channels?

Hello @lukejacksonn, thanks for your initiative, would you have time to look into merging this PR?

**Comment by lukejacksonn** [comment]
Hey @znk 👋 yep I have sat with Phil and talked through this a couple of time to try get my head around it. Have you used it at all and confirmed it all works as expected?

**Comment by lukejacksonn** [comment]
Thanks for this @kitten it is certainly an improvement over my manual method. I have just built for `16.11.0` and published to npm so this is now available at:

📦 [https://unpkg.com/es-react@16.11.0](https://unpkg.com/es-react@16.11.0)

I am going to merge this and then push my local on top of it 🙇

**Pull request merged**
