### PR TITLE
add react-dom-server to build

### LINKED ISSUE #2: ReactDOMServer
Thanks for putting this together! Would it be difficult to also expose ReactDOMServer? I'm wanting to experiment with SSR.

### PR DESCRIPTION
**Pull request by matthoffner**
Closes #2

### CODE REVIEW

**Comment by lukejacksonn** [comment]
Awesome stuff @matthoffner have you tested this for your use case and did it work?

**Comment by matthoffner** [comment]
Thanks @lukejacksonn - [I have a repo checked in with this working](https://github.com/matthoffner/es-react-ssr/blob/master/index.js). There is an issue I'm sorting out importing `React` on this server with `es-react`, but confirmed `ReactDOMServer` works.

**Comment by iAmNathanJ** [comment]
@matthoffner I think es-react package.json needs `"type": "module"` for this to work in node.

**Comment by matthoffner** [comment]
@iAmNathanJ Makes sense. Confirmed that fixed my issue, thanks!

**Comment by matthoffner** [comment]
@lukejacksonn I've confirmed this works for my use case. Included a reference in the README.

**Comment by lukejacksonn** [comment]
Hey @matthoffner I have been on vacation the past week, just catching up with GitHub notifications now. Thanks for confirming this I am going to consult some of my colleagues at Formidable before doing the next release, which hopefully will include this change. Thanks for your patience 🙇

**Comment by iAmNathanJ** [comment]
@matthoffner should this PR have the module entry in package.json for this to be useable in node?

@lukejacksonn while this will work for node, I think we will have to create an entry point for `react-dom/server.browser` (that doesn't hit the streaming apis) to work in  Deno. How would you feel about a follow up PR for that before the next release?

**Comment by lukejacksonn** [comment]
To be honest folks, it sounds like you both know a lot more about this than me! I tend not to touch the server side of things too much, especially when it comes to react.

Please do fork and modify this package to suit your needs and if you get something that _works_ then by all means PR it back and I will run it by some people. I do like the idea of deno and so it would be cool to help that community out if we can.

Thanks!

**Comment by matthoffner** [comment]
For clarification my use case is not for Deno. Just wanted to do React SSR without Babel and add here for completeness. The other fix @iAmNathanJ mentions can be done in a separate PR.

**Comment by iAmNathanJ** [comment]
@matthoffner no worries. I'll open a PR. Thanks!

**Comment by matthoffner** [comment]
@lukejacksonn Confirmed this works and closes #2. Not sure what else is needed.

**Pull request closed without merging**
